### ISSUE TITLE
سلام خسته نباشید من یه سرور از ولتر گرفتم هرکاری کردم نتونستم سرت بگیرم

### ISSUE THREAD

**Issue by Multivpnlive** [erfjab/ESSL#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by erfjab** [comment]
سلام وقت بخیر، لطفا لاگ‌هارو برام ارسال کنید.

**Comment by Multivpnlive** [comment]
![image](https://github.com/erfjab/ESSL/assets/151996045/890949b9-b8f2-4c14-88f1-7ba7f0ef8eb2)

**Comment by Multivpnlive** [comment]
> سلام وقت بخیر، لطفا لاگ‌هارو برام ارسال کنید. 

یه عکس ارسال کردم اومد براتون ؟

**Comment by erfjab** [comment]
با اسکریپت ما نگرفتید که عزیز. این دستی هست. درسته؟

**Comment by Multivpnlive** [comment]
> با اسکریپت ما نگرفتید که عزیز. این دستی هست. درسته؟ 
با اسکریپت شما گرفتم مشکل حل شد سرور فایروال داشت اسکریپت شما حرف نداره خیلی ممنونم ❤️
