### ISSUE TITLE
مرزبان

### ISSUE THREAD

**Issue by KanekiDevPro** [erfjab/ESSL#5]
سلام وقت بخیر این اسکریپت میتونه دوتا دامین برای مرزبان که یکی برای ساب و یکی برای پنل رو اوکی کنه ؟

**Comment by erfjab** [comment]
@Mohammadaminsdr سلام وقت بخیر، بله با روش مولتی دامین میتونید ssl دریافت کنید. فقط کافیه هنگام وارد کردن دامنه ها بین‌شون یک فاصله بزارید.

**Comment by KanekiDevPro** [comment]
ما با توجه به گفته شما انجام دادیم ولی فقط واسه دامین اولی رو میگیره و دومی گرفته نمیشه جای بایید ویرایش کرد ؟ فایل Caddy رو باید ویرایش کنیم ؟

**Comment by erfjab** [comment]
@Mohammadaminsdr همه‌ی دامنه ها در اسم و فایل دامنه‌ی اول ذخیره میشند که کلا در مولتی دامین ها پروسه به این شکله.
